//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLiner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeLiner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load {0}.
        /// </summary>
        internal static string ErrorCouldNotLoadFile {
            get {
                return ResourceManager.GetString("ErrorCouldNotLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty name.
        /// </summary>
        internal static string ErrorEmptyTimeLineName {
            get {
                return ResourceManager.GetString("ErrorEmptyTimeLineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist.
        /// </summary>
        internal static string ErrorFileDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not contain TimeLiner data.
        /// </summary>
        internal static string ErrorFileHasNoTimeLinerData {
            get {
                return ResourceManager.GetString("ErrorFileHasNoTimeLinerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in line {0}: {1}.
        /// </summary>
        internal static string ErrorInLine {
            get {
                return ResourceManager.GetString("ErrorInLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of columns.
        /// </summary>
        internal static string ErrorInvalidNumberOfColumns {
            get {
                return ResourceManager.GetString("ErrorInvalidNumberOfColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing timeline item name.
        /// </summary>
        internal static string ErrorMissingItemName {
            get {
                return ResourceManager.GetString("ErrorMissingItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing start time.
        /// </summary>
        internal static string ErrorMissingStartTime {
            get {
                return ResourceManager.GetString("ErrorMissingStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start-time lies behind end-time.
        /// </summary>
        internal static string ErrorStartTimeBehindEndTime {
            get {
                return ResourceManager.GetString("ErrorStartTimeBehindEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline already exists.
        /// </summary>
        internal static string ErrorTimelineAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorTimelineAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown color name: &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorUnknownColor {
            get {
                return ResourceManager.GetString("ErrorUnknownColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Item.
        /// </summary>
        internal static string TitleEditItem {
            get {
                return ResourceManager.GetString("TitleEditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string TitleNewFile {
            get {
                return ResourceManager.GetString("TitleNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        internal static string TitleNewItem {
            get {
                return ResourceManager.GetString("TitleNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Timeline.
        /// </summary>
        internal static string TitleNewTimeLine {
            get {
                return ResourceManager.GetString("TitleNewTimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Timeline.
        /// </summary>
        internal static string TitleRenameTimeline {
            get {
                return ResourceManager.GetString("TitleRenameTimeline", resourceCulture);
            }
        }
    }
}
