; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "TimeLiner"
#define MyAppPublisher "Christian Pistor"
#define MyAppExeName "TimeLiner.exe"
#if !FileExists("..\artifacts\publish\LICENSE")
  #error "The TimeLiner LICENSE file is missing from the publish directory."
#endif
#if !FileExists("..\artifacts\publish\THIRD-PARTY-NOTICES.txt")
  #error "The TimeLiner third-party notices are missing from the publish directory."
#endif
#if !FileExists("..\artifacts\publish\DOTNET-LICENSE.txt")
  #error "The .NET license is missing from the publish directory."
#endif
#if !FileExists("..\artifacts\publish\DOTNET-THIRD-PARTY-NOTICES.txt")
  #error "The .NET third-party notices are missing from the publish directory."
#endif
#if !FileExists("..\artifacts\installer\DOTNET-LICENSE.txt")
  #error "The Unicode .NET license file for the installer is missing."
#endif
#define MyAppVersion GetVersionNumbersString("..\artifacts\publish\" + MyAppExeName)
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".tli"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5C1DF68A-D660-4EA4-A632-BE442564C950}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
LicenseFile=..\artifacts\installer\DOTNET-LICENSE.txt
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputBaseFilename={#MyAppName}_{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
WizardLicense=Microsoft .NET License Terms
LicenseLabel=The license terms below apply only to the bundled Microsoft .NET components.
LicenseLabel3=The license terms below apply only to the bundled Microsoft .NET components. You must accept them before continuing with the installation.
LicenseAccepted=I &accept the license terms for the bundled Microsoft .NET components
LicenseNotAccepted=I &do not accept the license terms for the bundled Microsoft .NET components

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\artifacts\publish\*"; Excludes:"*.xml,*.pdb"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: "{#MyAppAssocExt}"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

